### ISSUE TITLE
If no one votes a veto resolution, quorum is not updated

### ISSUE THREAD

**Issue by vrde** [NeokingdomDAO/subgraph#2]
From what I understand, the quorum is updated when a contributor votes a draft resolution. Since no one voted on [Resolution#27](https://dao.teledisko.com/#/resolutions/27) in Teledisko, the quorum has not been updated, showing the resolution as "not adpoted":

![image](https://user-images.githubusercontent.com/134680/230747437-1e86e728-e540-46ed-9c09-5add33a76913.png)

That's a bit tricky because there are no events to listen to. If The Graph allows us to listen to new block events, then we can use it to check if the draft resolution voting period ended, and if so call `getResolutionResult`.

**Comment by stecb** [comment]
Can't we do the other way around? When the resolution is approved, we set the quorum reached by default if it's veto, and then update accordingly if votes come in?

Doing this ^ will fix teledisko's as well

**Comment by vrde** [comment]
> Can't we do the other way around? When the resolution is approved, we set the quorum reached by default if it's veto, and then update accordingly if votes come in?

Indeed, that's the right solution :)
